### ISSUE TITLE
К размышлению

### ISSUE THREAD

**Issue by wolflingorg** [Radvers/phplab-tasks#1]
# Константы - круто!
FIRST_QUARTER, SECOND_QUARTER, *_QUARTER - идеально вписываются так как именно эти константы будут использованы клиентами твоей функции, чтобы понять, что они получили в ответ. Для следующих поколений студентов обязательно добавим в задание.
MIN_YEAR и VALID_LENGTH в пределах класса можно было бы сделать приватными - они заменили бы собой "магические цифры" и помогли программисту, изучающему код, понять что значит 60 или 6

# https://github.com/Radvers/phplab-tasks/blob/master/src/01-basics.php#L19
Можно избежать создания дополнительной переменной вызовом return.
К примеру, как это сделано тут: https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html

# https://github.com/Radvers/phplab-tasks/blob/master/src/01-basics.php#L75
Я бы проверку перенес на самый верх. Зачем делать вычисления $halfLength, если мы не уверены, что $input is_numeric

Все размышления ниже - скорее дело вкуса ⬇

# https://github.com/Radvers/phplab-tasks/blob/master/src/01-basics.php#L82
Тут тоже можно было бы избежать создания переменных $firstHalf и $secondHalf:
return getSumOfDigits(substr($input, 0, $halfLength)) === getSumOfDigits(substr($input, -$halfLength))

# https://github.com/Radvers/phplab-tasks/blob/master/src/01-basics.php#L87
Переменную $digits тоже можно было не создавать:
foreach ((array) str_split($input) as $digit) {
        $sum += (int) $digit;
}

**Comment by Radvers** [comment]
@wolflingorg 
> MIN_YEAR и VALID_LENGTH в пределах класса можно было бы сделать приватными

Я и хотел их сделать приватными, но этот файл не является классом.

> Можно избежать создания дополнительной переменной вызовом return.

В какой-то из книг по php вычитал, что количество return должно быть минимальным поскольку повышает сложность понимания и поддержки приложения. Есть случаи когда без этого не обойтись, но в конкретном кейсе мне показалось что одного достаточно.

Выполнил правки по данным рекомендациям.
